### PR TITLE
Add 'make' to the instructions (to make booster.bin).

### PR DESCRIPTION
**Pull request by tcal-x**
Fixes issue #187 . 

Also fix a typo in flash addresses.

Signed-off-by: Tim Callahan <tcal@google.com>

### CODE REVIEW

**Comment by mithro** [comment]
@xobs - Does this look right?

**Review by xobs — APPROVED** [review]
It looks correct to me!

**Comment by tcal-x** [comment]
@xobs -- could I change the Makefile so that the default `make` target both 

- compiles `make-booster`, 
- and then uses it to construct `booster.bin`?     

Then we could get rid of the explicit `cc` command in the instructions.

Or do you prefer I leave it the way it is?

**Comment by xobs** [comment]
I want to make it at least slightly inconvenient. It's a process that carries with it the extremely real possibility of bricking a device with no easy way back.

**Comment by tcal-x** [comment]
Makes sense.   I'll merge it the way it is.

**Pull request merged**
